
services:
  app:
    image: pytorch/pytorch:latest
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["bash", "-c", "pip install -r requirements.txt && tail -f /dev/null"]

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.3.2
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/data

  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    ports:
      - "8080:8080"
    environment:
      - CLEARML_SERVER_IP=clearml
      - CLEARML_WEB_HOST=http://localhost:8080
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  qdrant_data:

